markdown: rdiscount
permalink: /:title/
url: http://ruizhengyu.github.io
name: 数域K上N维线性空间
author: ruizhengyu
qq: 767496479
email: ruizhengyu@gmail.com
duoshuo: rui
beian: 
cnzz: 
weibo: 2237065581
github: ruizhengyu
pygments: true
safe: true
paginate: 20
about: "这里是我的个人博客，创建于 2016 年。<br /><br />这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
