markdown: rdiscount
permalink: /:title/
url: http://www.personalsite.cn
name: 数域K上N维线性空间
author: ruizhengyu
qq: 767496479
email: ruizhengyu@gmail.com
duoshuo: rui
beian: 
cnzz: 1257366192
weibo: 2237065581
github: ruizhengyu
pygments: true
safe: true
paginate: 20
about: "这里是我的个人博客。"
